version: '3.8'

services:
  pokemon_bd:
    image: mysql:8.0
    container_name: pokemon_bd
    restart: always
    environment:
      MYSQL_DATABASE: 'pokemon_bd'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3306'
